---
output: html_document
---

---
title: "Codebook describing a new analysis of the Human Activity Recognition Using Smartphones Dataset"
---


This code book describes the variables, the data, and the transformations performed to clean up the original data.

## Data Set Description 

The present analysis is based on a data set coming from the reference: 
Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012. 


the data are downloaded from :
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip


The original experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. 
Each person wearing a smartphone (Samsung Galaxy S II) on the waist performed six activities:

* WALKING, 
* WALKING_UPSTAIRS, 
* WALKING_DOWNSTAIRS, 
* SITTING, 
* STANDING, 
* LAYING

Using its embedded accelerometer and gyroscope, the original authors captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

More details can be found directly in the [features_info.txt] http://archive.ics.uci.edu/ml/machine-learning-databases/00240/UCI%20HAR%20Dataset.names)

In the present analysis not all the original features were considered. Only the calculated  mean and standand deviation of some features were retained. The features were selected extracting only the measurements on the mean and standard deviation for each measurement.


### For each record it is provided:

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

### Units

- The units used for the accelerations (total and body) are 'g's (gravity of earth -> 9.80665 m/seg2).
- The gyroscope units are rad/seg.

### Notes

- Features are normalized and bounded within [-1,1].
- Each feature vector is a row on the text file.

## Transformation

The script calculated the averaged features for each subject and each activity type. At the end, a tidy data set of 180 rows (6 activity types x 30 subjects ID) and 88 features is provided.