---
output: html_document
---
As required for this final project, I include this README.rmd in the repo which contain 4 files. This readme explains how all of the scripts work and how they are connected.

## Readme.rmd 
  This file. 
  
## Run_analysis.R 
this script does the following:

1. Read the original data
2. Merges the training and the test sets to create one data set.
3. Extracts only the measurements on the mean and standard deviation for each measurement.
4. Uses descriptive activity names to name the activities in the data set
5. Appropriately labels the data set with descriptive variable names.
6. creates a second, independent tidy data set with the average of each variable for each activity and each subject.
7. Save the data set as a txt file 

## codebook.rmd

This file describes the variables, the data, and any transformations or work  performed to clean up the data

## final.txt

This is final output of the Run_analysis.r script containing the averaged features for each subject and each activity type.
